#!/bin/bash
# Generate a PR message using Cline CLI
# Usage: ./generate-pr.sh [base-branch] [output-file]
# Example: ./generate-pr.sh dev PR_DESCRIPTION.md

set -euo pipefail

BASE_BRANCH="${1:-dev}"
OUTPUT_FILE="${2:-}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Get the current branch name
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

# Find the merge base (where the branch diverged from base)
MERGE_BASE=$(git merge-base "$BASE_BRANCH" HEAD 2>/dev/null || echo "")

if [ -z "$MERGE_BASE" ]; then
  echo "Error: Could not find common ancestor between $CURRENT_BRANCH and $BASE_BRANCH" >&2
  exit 1
fi

# Get changes since branching from base
DIFF_STAT=$(git diff --stat "$MERGE_BASE"..HEAD)
FILES_CHANGED=$(git diff --name-only "$MERGE_BASE"..HEAD)
COMMIT_MESSAGES=$(git log --oneline "$MERGE_BASE"..HEAD)
COMMIT_COUNT=$(git rev-list --count "$MERGE_BASE"..HEAD)

echo "# Analyzing $COMMIT_COUNT commits since branching from $BASE_BRANCH..." >&2

# Read the PR template
TEMPLATE=$(cat "$REPO_ROOT/.github/PULL_REQUEST_TEMPLATE.md" 2>/dev/null || echo "")

# Write context to a temp file for Cline to read
CONTEXT_FILE=$(mktemp)
cat > "$CONTEXT_FILE" << EOF
Generate a GitHub Pull Request description for the following changes.

## SOURCE BRANCH: $CURRENT_BRANCH
## TARGET BRANCH: $BASE_BRANCH
## NUMBER OF COMMITS: $COMMIT_COUNT

## COMMIT MESSAGES:
$COMMIT_MESSAGES

## FILES CHANGED:
$FILES_CHANGED

## DIFF STATISTICS:
$DIFF_STAT

## PR TEMPLATE TO FOLLOW:
$TEMPLATE

INSTRUCTIONS:
1. Follow the PR template structure exactly
2. Check appropriate checkboxes with [x] based on what changed
3. Fill in the Description based on the commits
4. List the Changes Made from the commit messages
5. Output ONLY the completed markdown, nothing else
EOF

echo "# Running Cline CLI..." >&2

# Run Cline with the context file
cline -y "Read $CONTEXT_FILE and generate a PR description following the template. Output only markdown." --mode act 2>/dev/null || {
  echo "# Cline failed, falling back to basic template..." >&2
  cat << ENDPR
# Pull Request

## Description
Branch \`$CURRENT_BRANCH\` → \`$BASE_BRANCH\` ($COMMIT_COUNT commits)

## Type of Change
- [x] ✨ New feature (non-breaking change that adds functionality)

## Changes Made
$(echo "$COMMIT_MESSAGES" | sed 's/^[a-f0-9]* /- /')

## Files Changed
\`\`\`
$DIFF_STAT
\`\`\`

## Checklist
- [x] My code follows the project's coding standards
- [x] I have performed a self-review of my code

---
*Generated by InFoundry*
ENDPR
}

# Cleanup
rm -f "$CONTEXT_FILE"
